import type { DrivingSide } from '@transitmapper/core/model/system';

// Complete ISO 3166-1 set for left-hand traffic, including separately coded
// territories. This follows Rapid Editor country-coder's maintained
// `driveSide` data; its non-ISO Ascension, Sark, and Tristan codes are folded
// into their ISO parents SH and GG because Nominatim returns ISO country_code.
const LEFT_DRIVING_COUNTRIES = new Set([
  'ag',
  'ai',
  'au',
  'bb',
  'bd',
  'bm',
  'bn',
  'bs',
  'bt',
  'bw',
  'cc',
  'ck',
  'cx',
  'cy',
  'dm',
  'fj',
  'fk',
  'gb',
  'gd',
  'gg',
  'gs',
  'gy',
  'hk',
  'hm',
  'id',
  'ie',
  'im',
  'in',
  'je',
  'jm',
  'jp',
  'ke',
  'ki',
  'kn',
  'ky',
  'lc',
  'lk',
  'ls',
  'mo',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'my',
  'mz',
  'na',
  'nf',
  'np',
  'nr',
  'nu',
  'nz',
  'pg',
  'pk',
  'pn',
  'sb',
  'sc',
  'sg',
  'sh',
  'sr',
  'sz',
  'tc',
  'th',
  'tk',
  'tl',
  'to',
  'tt',
  'tv',
  'tz',
  'ug',
  'vc',
  'vg',
  'vi',
  'ws',
  'za',
  'zm',
  'zw',
]);

/** Infer only the initial convention; an existing document remains authoritative without a country. */
export function drivingSideForCountry(countryCode: string | undefined): DrivingSide | undefined {
  if (!countryCode) return undefined;
  return LEFT_DRIVING_COUNTRIES.has(countryCode.toLowerCase()) ? 'left' : 'right';
}
