// TypeScript rather than JavaScript, which is what every other config file in
// this repository is and what `check:config` enforces. ESLint loads this
// through jiti; without that dependency it resolves to nothing and every rule
// below silently stops applying.
//
// Deliberately free of repository-specific paths apart from the scoped blocks
// at the end, so the org's other repositories can adopt the baseline unchanged.
// `website` has no ESLint at all, which makes this the org's first
// configuration and therefore the shared one.
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import transitmapper from '@transitmapper/eslint-plugin';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/.wrangler/**',
      '.claude/worktrees/**',
      // Generated by `wrangler types` from wrangler.toml. Linting vendored
      // runtime typings reports on Cloudflare's code, not ours.
      '**/worker-configuration.d.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  // Scoped to the React app. Three files already carried
  // `eslint-disable-next-line react-hooks/exhaustive-deps` comments, which
  // ESLint reports as errors when the rule they name does not exist — the
  // suppressions were written against a plugin nobody had installed.
  //
  // The two classic rules only, listed explicitly rather than spreading one
  // of the plugin's presets. As of eslint-plugin-react-hooks 7, every preset
  // — `recommended` included — carries the React Compiler rule set (purity,
  // immutability, set-state-in-effect, manual memoization), which reports 14
  // findings here. Those are a real decision about how this app is written,
  // and belong in their own change rather than riding along with a baseline.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
    },
  },
  {
    rules: {
      // Underscore-prefixed bindings are an intentional "declared, unused"
      // signal; everything else unused is a mistake worth surfacing.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // The rule targets namespaces used as a module system, which is the
      // real anti-pattern. `declare namespace` is declaration merging, and
      // augmenting an ambient type such as `Cloudflare.Env` has no ES module
      // equivalent — there is no other way to express it.
      '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
    },
  },
  // Repository-specific rules, each encoding something AGENTS.md previously
  // only asserted in prose. Scoped to the package the rule is about.
  {
    files: ['packages/core/**/*.ts'],
    plugins: { transitmapper },
    rules: {
      'transitmapper/core-runtime-purity': 'error',
    },
  },

  // Last, so it switches off every stylistic rule that would fight Prettier.
  prettier,
);
