import { createHash } from 'node:crypto';
import { appIconPng, appIconSvg, type AppIconKind } from './app-icon';

export interface ManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose: 'any' | 'maskable';
}

export interface InstallIconAsset {
  role: InstallIconRole;
  name: string;
  contents: Buffer;
  manifest: ManifestIcon;
}

export interface InstallIconAssetSet {
  revision: string;
  assets: InstallIconAsset[];
}

type InstallIconRole =
  'regular-svg' | 'regular-192' | 'regular-512' | 'maskable-svg' | 'maskable-192' | 'maskable-512';

interface UnversionedInstallIcon {
  role: InstallIconRole;
  kind: AppIconKind;
  size: 'any' | 192 | 512;
  contents: Buffer;
}

const INSTALL_ICON_ORDER: readonly Omit<UnversionedInstallIcon, 'contents'>[] = [
  { role: 'regular-svg', kind: 'regular', size: 'any' },
  { role: 'regular-192', kind: 'regular', size: 192 },
  { role: 'regular-512', kind: 'regular', size: 512 },
  { role: 'maskable-svg', kind: 'maskable', size: 'any' },
  { role: 'maskable-192', kind: 'maskable', size: 192 },
  { role: 'maskable-512', kind: 'maskable', size: 512 },
];

async function unversionedInstallIcons(): Promise<UnversionedInstallIcon[]> {
  return Promise.all(
    INSTALL_ICON_ORDER.map(async (icon) => ({
      ...icon,
      contents:
        icon.size === 'any'
          ? Buffer.from(appIconSvg({ kind: icon.kind, theme: 'adaptive' }))
          : await appIconPng({ kind: icon.kind, theme: 'light', size: icon.size }),
    })),
  );
}

/**
 * Length prefixes make the digest input unambiguous while retaining both
 * semantic role and exact generated bytes. One revision covers the full set,
 * so the manifest can never mix files from two icon identities.
 */
function iconRevision(icons: readonly UnversionedInstallIcon[]): string {
  const hash = createHash('sha256');
  for (const icon of icons) {
    hash.update(icon.role);
    hash.update('\0');
    hash.update(String(icon.contents.byteLength));
    hash.update('\0');
    hash.update(icon.contents);
  }
  return hash.digest('hex').slice(0, 12);
}

function assetName(icon: UnversionedInstallIcon, revision: string): string {
  const prefix = icon.kind === 'maskable' ? 'app-icon-maskable' : 'app-icon';
  const suffix = icon.size === 'any' ? '.svg' : `-${icon.size}.png`;
  return `${prefix}-${revision}${suffix}`;
}

function manifestIcon(icon: UnversionedInstallIcon, name: string): ManifestIcon {
  return {
    src: `/icons/${name}`,
    sizes: icon.size === 'any' ? 'any' : `${icon.size}x${icon.size}`,
    type: icon.size === 'any' ? 'image/svg+xml' : 'image/png',
    purpose: icon.kind === 'maskable' ? 'maskable' : 'any',
  };
}

export async function generateInstallIconAssets(): Promise<InstallIconAssetSet> {
  const icons = await unversionedInstallIcons();
  const revision = iconRevision(icons);
  return {
    revision,
    assets: icons.map((icon) => {
      const name = assetName(icon, revision);
      return {
        role: icon.role,
        name,
        contents: icon.contents,
        manifest: manifestIcon(icon, name),
      };
    }),
  };
}
