#!/usr/bin/env tsx
/**
 * Fails when worker-configuration.d.ts no longer describes the bindings in
 * wrangler.toml.
 *
 * The file is generated by `wrangler types` and committed, because CI has to
 * typecheck without invoking wrangler. That makes it the classic stale
 * artefact: change a binding in wrangler.toml, forget to regenerate, and the
 * types keep describing the old deployment while everything still compiles.
 *
 * It compares the binding declarations, not the bytes. A byte comparison
 * fails for two reasons that have nothing to do with staleness: the header
 * embeds the exact command line used and a hash of it, so regenerating to a
 * different path always differs, and quoting style is not stable across the
 * generator and the formatter. The set of `name: Type` pairs is the part
 * that carries meaning.
 *
 * Registered as a Turborepo task with wrangler.toml declared as an input, so
 * it only re-runs when that file actually changes.
 */
import { execFileSync } from 'node:child_process';
import { readFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';

const WORKER_DIR = resolve(import.meta.dirname, '..');
const COMMITTED = resolve(WORKER_DIR, 'worker-configuration.d.ts');
const REGENERATED = resolve(tmpdir(), `worker-configuration.check.${process.pid}.d.ts`);

/**
 * Pulls the generated env interface out as normalised `name: Type` lines.
 * Quotes are unified and whitespace collapsed so formatting cannot make an
 * up-to-date file look stale.
 */
function bindings(source: string): string[] {
  const match = /interface __BaseEnv_Env \{([^}]*)\}/.exec(source);
  if (!match) return [];
  return match[1]
    .split('\n')
    .map((line) => line.trim().replace(/"/g, "'").replace(/\s+/g, ' '))
    .filter((line) => line.length > 0)
    .sort();
}

async function main(): Promise<void> {
  try {
    execFileSync('npx', ['wrangler', 'types', REGENERATED], {
      cwd: WORKER_DIR,
      stdio: 'pipe',
    });
  } catch (err) {
    console.error('\nCould not regenerate types to compare against.\n');
    console.error(err);
    process.exit(1);
  }

  const [committedSource, regeneratedSource] = await Promise.all([
    readFile(COMMITTED, 'utf8').catch(() => ''),
    readFile(REGENERATED, 'utf8'),
  ]);
  await rm(REGENERATED, { force: true });

  const committed = bindings(committedSource);
  const regenerated = bindings(regeneratedSource);

  if (regenerated.length === 0) {
    console.error('\nCould not find __BaseEnv_Env in the regenerated types.');
    console.error('The generator output shape changed; this check needs updating.\n');
    process.exit(1);
  }

  if (committed.join('\n') !== regenerated.join('\n')) {
    console.error('\nworker-configuration.d.ts is stale.\n');
    console.error('  It no longer describes the bindings in wrangler.toml, so the');
    console.error('  compiler sees a different deployment than the one configured.\n');
    console.error('  committed:');
    for (const line of committed) console.error(`    ${line}`);
    console.error('  wrangler.toml:');
    for (const line of regenerated) console.error(`    ${line}`);
    console.error('\n  fix:  pnpm --filter @transitmapper/worker types\n');
    process.exit(1);
  }

  console.log(`worker-configuration.d.ts matches wrangler.toml (${committed.length} bindings).`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
