import type {
  PerfProfileId,
  PerfProtocol,
  PerfRunMode,
  PerfScenario,
  PerfScenarioId,
  PerfViewport,
} from './types';

const PROFILE_VIEWPORTS: Record<PerfProfileId, PerfViewport> = {
  desktop: {
    width: 1_440,
    height: 900,
    deviceScaleFactor: 1,
  },
  mobile: {
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
  },
};

export function createPerfProtocol(
  profile: PerfProfileId,
  runMode: PerfRunMode = 'audit',
): PerfProtocol {
  return {
    profile,
    browser: 'Google Chrome',
    browserChannel: 'chrome',
    headed: true,
    cpuThrottlingRate: 4,
    cache: 'cleared-before-cold-load-then-enabled',
    viewport: PROFILE_VIEWPORTS[profile],
    network: {
      name: 'Fast 4G',
      downloadThroughputBytesPerSecond: (4 * 1_024 * 1_024) / 8,
      uploadThroughputBytesPerSecond: (3 * 1_024 * 1_024) / 8,
      latencyMs: 20,
    },
    // Pull-request smoke runs prove the complete cold/warm RTC journey once.
    // Repetition belongs to a deliberate audit, where it can support a
    // statistical timing decision instead of spending Actions minutes on
    // every branch update.
    warmupRuns: runMode === 'smoke' ? 0 : 1,
    measuredRuns: runMode === 'smoke' ? 1 : 5,
    warmReloadsPerMeasuredRun: 1,
  };
}

export const PERF_PROTOCOL: PerfProtocol = createPerfProtocol('desktop');

export const PERF_SCENARIOS: Record<PerfScenarioId, PerfScenario> = {
  small: {
    id: 'small',
    surface: 'editor',
    fixtureId: 'small',
    label: 'Small sketch',
    description: 'A small advocacy sketch that catches fixed startup costs.',
    path: '/',
    readySelector: '.maplibregl-canvas',
    fixture: {
      ways: 24,
      points: 240,
      stations: 30,
      patterns: 6,
    },
    absoluteBudgets: {
      loadMs: 3_500,
      firstContentfulPaintMs: 2_000,
      largestContentfulPaintMs: 2_500,
      firstMapCanvasMs: 3_500,
      cumulativeLayoutShift: 0.1,
      longTaskTotalMs: 750,
      transferBytes: 2_500_000,
      inputToNextPaintP95Ms: 50,
      paintedFrameP95Ms: 16.7,
      paintedFramesOver33Ratio: 0.01,
      maxUnexpectedLongTaskMs: 50,
      warmLoadMs: 3_500,
      warmLargestContentfulPaintMs: 2_500,
      warmCumulativeLayoutShift: 0.1,
      warmInputToNextPaintP95Ms: 50,
    },
  },
  dense: {
    id: 'dense',
    surface: 'editor',
    fixtureId: 'dense',
    label: 'Dense city',
    description: 'A dense urban network between a sketch and a full agency import.',
    path: '/',
    readySelector: '.maplibregl-canvas',
    fixture: {
      ways: 600,
      points: 18_000,
      stations: 800,
      patterns: 60,
    },
    absoluteBudgets: {
      loadMs: 5_000,
      firstContentfulPaintMs: 2_500,
      largestContentfulPaintMs: 2_500,
      firstMapCanvasMs: 5_000,
      cumulativeLayoutShift: 0.1,
      longTaskTotalMs: 1_800,
      transferBytes: 4_000_000,
      inputToNextPaintP95Ms: 50,
      paintedFrameP95Ms: 16.7,
      paintedFramesOver33Ratio: 0.01,
      maxUnexpectedLongTaskMs: 50,
      warmLoadMs: 5_000,
      warmLargestContentfulPaintMs: 2_500,
      warmCumulativeLayoutShift: 0.1,
      warmInputToNextPaintP95Ms: 50,
    },
  },
  rtc: {
    id: 'rtc',
    surface: 'editor',
    fixtureId: 'rtc',
    label: 'RTC-shaped agency import',
    description: 'The scale of the RTC Southern Nevada fixture: thousands of ways and stops.',
    path: '/',
    readySelector: '.maplibregl-canvas',
    fixture: {
      ways: 3_800,
      points: 121_000,
      stations: 3_800,
      patterns: 285,
    },
    absoluteBudgets: {
      loadMs: 8_000,
      firstContentfulPaintMs: 3_500,
      largestContentfulPaintMs: 2_500,
      firstMapCanvasMs: 7_500,
      cumulativeLayoutShift: 0.1,
      longTaskTotalMs: 3_500,
      transferBytes: 6_000_000,
      inputToNextPaintP95Ms: 50,
      paintedFrameP95Ms: 16.7,
      paintedFramesOver33Ratio: 0.01,
      maxUnexpectedLongTaskMs: 50,
      warmLoadMs: 8_000,
      warmLargestContentfulPaintMs: 2_500,
      warmCumulativeLayoutShift: 0.1,
      warmInputToNextPaintP95Ms: 50,
    },
  },
  share: {
    id: 'share',
    surface: 'share',
    fixtureId: 'rtc',
    label: 'RTC-shaped share page',
    description: 'The read-only public share surface with an agency-scale snapshot.',
    path: '/s/perfshare',
    readySelector: '.ro-name',
    fixture: {
      ways: 3_800,
      points: 121_000,
      stations: 3_800,
      patterns: 285,
    },
    absoluteBudgets: {
      loadMs: 8_000,
      firstContentfulPaintMs: 3_500,
      largestContentfulPaintMs: 2_500,
      firstMapCanvasMs: 7_500,
      cumulativeLayoutShift: 0.1,
      longTaskTotalMs: 3_500,
      transferBytes: 6_000_000,
      inputToNextPaintP95Ms: 50,
      paintedFrameP95Ms: 16.7,
      paintedFramesOver33Ratio: 0.01,
      maxUnexpectedLongTaskMs: 50,
      warmLoadMs: 8_000,
      warmLargestContentfulPaintMs: 2_500,
      warmCumulativeLayoutShift: 0.1,
      warmInputToNextPaintP95Ms: 50,
    },
  },
  embed: {
    id: 'embed',
    surface: 'embed',
    fixtureId: 'rtc',
    label: 'RTC-shaped embed',
    description: 'The small read-only embed entry with an agency-scale snapshot.',
    path: '/e/perfembed',
    readySelector: '.maplibregl-canvas',
    fixture: {
      ways: 3_800,
      points: 121_000,
      stations: 3_800,
      patterns: 285,
    },
    absoluteBudgets: {
      loadMs: 7_000,
      firstContentfulPaintMs: 3_000,
      largestContentfulPaintMs: 2_500,
      firstMapCanvasMs: 6_500,
      cumulativeLayoutShift: 0.1,
      longTaskTotalMs: 3_000,
      transferBytes: 4_000_000,
      inputToNextPaintP95Ms: 50,
      warmLoadMs: 7_000,
      warmLargestContentfulPaintMs: 2_500,
      warmCumulativeLayoutShift: 0.1,
      warmInputToNextPaintP95Ms: 50,
    },
  },
};

export const PERF_SCENARIO_LIST: PerfScenario[] = [
  PERF_SCENARIOS.small,
  PERF_SCENARIOS.dense,
  PERF_SCENARIOS.rtc,
  PERF_SCENARIOS.share,
  PERF_SCENARIOS.embed,
];
