/**
 * The org's ESLint baseline, as two functions.
 *
 * A repository consuming this writes one import and one call:
 *
 * ```ts
 * import { defineTypeAwareConfig } from '@transitmapper/config-eslint';
 * export default defineTypeAwareConfig(import.meta.dirname);
 * ```
 *
 * Anything repository-specific — a plugin scoped to one application, a rule
 * that only makes sense for one package — is passed as extra config objects
 * and lands between the baseline and the Prettier reset, which is the only
 * position where a scoped override both sees the baseline and cannot be
 * undone by it.
 *
 * The reason this is a package rather than a file to copy: an ESLint config is
 * where a repository's standards live, and a copied config diverges the first
 * time somebody fixes something in one repository and not the others. There is
 * no way to notice that drift, because both files keep working.
 */
import eslint from '@eslint/js';
import comments from '@eslint-community/eslint-plugin-eslint-comments';
import prettier from 'eslint-config-prettier';
// ESLint core's own composer. `tseslint.config()` does the same job and is
// deprecated in favour of this one; aliased because this module exports a
// `defineConfig` of its own.
import { defineConfig as compose } from 'eslint/config';
import tseslint from 'typescript-eslint';

/** What the composer accepts, and what callers may pass as overrides. */
export type ConfigInput = Parameters<typeof compose>[number];

/** What the composer returns, and what an `eslint.config.ts` exports. */
export type ConfigArray = ReturnType<typeof compose>;

/**
 * Paths no repository wants linted. Build output and dependencies are obvious;
 * the last two are not.
 */
const IGNORES: ConfigInput = {
  ignores: [
    '**/dist/**',
    '**/node_modules/**',
    '**/.turbo/**',
    '**/.wrangler/**',
    // Agent worktrees are full checkouts of the same repository. Linting them
    // reports every finding a second time, against a path nobody edits.
    '.claude/worktrees/**',
    // Generated by `wrangler types` from wrangler.toml. Linting vendored
    // runtime typings reports on Cloudflare's code, not ours.
    '**/worker-configuration.d.ts',
  ],
};

/**
 * Rules about the escape hatch itself. Every rule a config adds can be switched
 * off one line at a time, so the suppressions have to be as accountable as the
 * code — otherwise the first inconvenient rule gets silenced and nothing
 * announces it.
 *
 * The plugin's `recommended` preset is deliberately not spread. It carries
 * `no-unused-disable`, which reports the same defect as ESLint's own
 * `reportUnusedDisableDirectives`, and two tools reporting one defect teaches
 * people to ignore both.
 */
const SUPPRESSION_HYGIENE: ConfigInput = {
  linterOptions: {
    // A disable that no longer suppresses anything outlived the code it was
    // written for. Left at the default `warn` it accumulates silently, which is
    // how a suppression list stops describing the codebase.
    reportUnusedDisableDirectives: 'error',
  },
  plugins: { '@eslint-community/eslint-comments': comments },
  rules: {
    // A bare `/* eslint-disable */` switches off every rule for the rest of the
    // file, including rules written years after the comment.
    '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
    '@eslint-community/eslint-comments/no-duplicate-disable': 'error',
    // Not in the plugin's `recommended`, and the reason to depend on it: a
    // disable must say why in a `-- reason` suffix. Which rule is being
    // disabled is already in the comment; why is the part that goes stale, and
    // the part a reviewer needs in order to judge whether it still holds.
    '@eslint-community/eslint-comments/require-description': 'error',
  },
};

/** Two departures from what typescript-eslint's presets set. */
const TYPESCRIPT_ADJUSTMENTS: ConfigInput = {
  rules: {
    // Underscore-prefixed bindings are an intentional "declared, unused"
    // signal; everything else unused is a mistake worth surfacing.
    '@typescript-eslint/no-unused-vars': [
      'error',
      { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
    ],
    // The rule targets namespaces used as a module system, which is the real
    // anti-pattern. `declare namespace` is declaration merging, and augmenting
    // an ambient type such as `Cloudflare.Env` has no ES module equivalent —
    // there is no other way to express it.
    '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
  },
};

/**
 * Four departures from `strictTypeChecked` and `stylisticTypeChecked`, each
 * one measured rather than guessed. Turned on untouched, those presets reported
 * 1,973 findings on this repository; these four accounted for 973 of them, and
 * almost none described a defect.
 *
 * The test applied to each was: does a finding name something that could be
 * wrong at runtime, or does it name a style the codebase chose on purpose? A
 * rule that mostly reports the second kind teaches people that the linter is
 * wrong, which is how they learn to ignore the findings that matter.
 */
const TYPE_AWARE_ADJUSTMENTS: ConfigInput = {
  rules: {
    // 495 findings, nearly all `onClick={() => setOpen(true)}`. The confusion
    // the rule guards against is a void value being *used* — assigned, or
    // returned from something whose type suggests it produced a result — and
    // both options below keep exactly that.
    '@typescript-eslint/no-confusing-void-expression': [
      'error',
      { ignoreArrowShorthand: true, ignoreVoidOperator: true },
    ],
    // 293 findings, because the default rejects a number in a template. The
    // bug this rule exists for is `${anObject}` becoming "[object Object]";
    // `${count}` is unambiguous in every language that has interpolation.
    '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
    // 126 findings. An empty function is a no-op default — `onClose = () => {}`
    // — not a mistake. The rule cannot tell a deliberate no-op from a stub,
    // and a stub is caught by the test that fails instead.
    '@typescript-eslint/no-empty-function': 'off',
    // 59 findings, and purely which spelling of an array type to use. This
    // repository delegates formatting to Prettier precisely so nobody argues
    // about it in review; a lint rule is the same argument with a build
    // failure attached.
    '@typescript-eslint/array-type': 'off',
  },
};

function assemble(typeAware: ConfigInput[], extra: ConfigInput[]): ConfigArray {
  return compose(
    IGNORES,
    eslint.configs.recommended,
    ...typeAware,
    SUPPRESSION_HYGIENE,
    TYPESCRIPT_ADJUSTMENTS,
    ...extra,
    // Last, so it switches off every stylistic rule that would fight Prettier.
    prettier,
  );
}

/**
 * The baseline without a type checker: syntax-only rules, fast, and usable in a
 * repository that has no TypeScript project covering every file.
 *
 * Prefer {@link defineTypeAwareConfig}. Most of what a rule can prove from
 * syntax alone the compiler already proves, so this leaves the valuable half on
 * the table.
 */
export function defineConfig(...extra: ConfigInput[]): ConfigArray {
  return assemble([...tseslint.configs.recommended], extra);
}

/**
 * The baseline plus every rule that needs to know what a value *is*: a missing
 * `await` on a promise-returning call, a null check on something the types say
 * is never null, an `async` function passed where a `void` callback is
 * expected. None of those are visible to a parser, and all three are ordinary
 * mistakes rather than exotic ones.
 *
 * `rootDir` is the directory holding the consuming `eslint.config.ts`, which is
 * always `import.meta.dirname`. TypeScript resolves each file by walking up to
 * the nearest `tsconfig.json` — and only that name, never a differently named
 * config — so every file a repository lints must be covered by one. A file that
 * is not gets rejected rather than checked, which is why this repository's
 * `tsconfig.json` is the wide config and `tsconfig.build.json` is the narrow
 * one.
 */
export function defineTypeAwareConfig(rootDir: string, ...extra: ConfigInput[]): ConfigArray {
  return assemble(
    [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
      { languageOptions: { parserOptions: { projectService: true, tsconfigRootDir: rootDir } } },
      TYPE_AWARE_ADJUSTMENTS,
      // Last of the type-aware block, and the order is load-bearing.
      //
      // typescript-eslint's presets match every file ESLint visits, not only
      // TypeScript ones, so a plain `.mjs` — this repository's Prettier config
      // — gets handed to rules that demand a type checker, and ESLint aborts
      // the whole run rather than reporting a finding. Anything that switches a
      // type-aware rule back on has to come before this, or it switches it back
      // on for those files too.
      { files: ['**/*.{js,mjs,cjs}'], ...tseslint.configs.disableTypeChecked },
    ],
    extra,
  );
}
